# Generated by Django 4.2.3 on 2024-01-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_followers_follower_remove_followers_following_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('follower', 'following')},
        ),
    ]
